---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: wordpress-project
type: Opaque
data:
  db_root_password: QmVvbmNha3QwcAo=
  db_password: d29yZHByZXNzCg==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deployment
  namespace: wordpress-project
spec:
  selector:
    matchLabels:
      app: mariadb-app
  template:
    metadata:
      labels:
        app: mariadb-app
    spec:
      containers:
      - name: mariadb-app
        image: mariadb:10.6.4-focal
        resources:
          limits:
            memory: "512Mi"
            cpu: "100m"
        ports:
        - containerPort: 3306
          name: mariadb-port
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: mariadb-storage
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: db_root_password
        - name: MARIADB_DATABASE
          value: "wordpress"
        - name: MYSQL_USER
          value: "wordpress"
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: db_password
              name: mariadb-secret
      volumes:
        - name: mariadb-storage
          persistentVolumeClaim:
            claimName: mariadb-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
  namespace: wordpress-project
spec:
  resources:
    requests:
      storage: 512Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
  namespace: wordpress-project
spec:
  selector:
    app: mariadb-app
  ports:
  - port: 3306
    targetPort: mariadb-port